// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/Sakura-Industries-LLC/release/internal/stage/pkgrepo"
)

// NewMockObjectStore creates a new instance of MockObjectStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectStore {
	mock := &MockObjectStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObjectStore is an autogenerated mock type for the ObjectStore type
type MockObjectStore struct {
	mock.Mock
}

type MockObjectStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectStore) EXPECT() *MockObjectStore_Expecter {
	return &MockObjectStore_Expecter{mock: &_m.Mock}
}

// Stat provides a mock function for the type MockObjectStore
func (_mock *MockObjectStore) Stat(ctx context.Context, name string) (pkgrepo.StoredContent, bool, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 pkgrepo.StoredContent
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (pkgrepo.StoredContent, bool, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) pkgrepo.StoredContent); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(pkgrepo.StoredContent)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, name)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockObjectStore_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockObjectStore_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockObjectStore_Expecter) Stat(ctx any, name any) *MockObjectStore_Stat_Call {
	return &MockObjectStore_Stat_Call{Call: _e.mock.On("Stat", ctx, name)}
}

func (_c *MockObjectStore_Stat_Call) Run(run func(ctx context.Context, name string)) *MockObjectStore_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectStore_Stat_Call) Return(storedContent pkgrepo.StoredContent, b bool, err error) *MockObjectStore_Stat_Call {
	_c.Call.Return(storedContent, b, err)
	return _c
}

func (_c *MockObjectStore_Stat_Call) RunAndReturn(run func(ctx context.Context, name string) (pkgrepo.StoredContent, bool, error)) *MockObjectStore_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function for the type MockObjectStore
func (_mock *MockObjectStore) Upload(ctx context.Context, request pkgrepo.UploadRequest) error {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pkgrepo.UploadRequest) error); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockObjectStore_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockObjectStore_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - request pkgrepo.UploadRequest
func (_e *MockObjectStore_Expecter) Upload(ctx any, request any) *MockObjectStore_Upload_Call {
	return &MockObjectStore_Upload_Call{Call: _e.mock.On("Upload", ctx, request)}
}

func (_c *MockObjectStore_Upload_Call) Run(run func(ctx context.Context, request pkgrepo.UploadRequest)) *MockObjectStore_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pkgrepo.UploadRequest
		if args[1] != nil {
			arg1 = args[1].(pkgrepo.UploadRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectStore_Upload_Call) Return(err error) *MockObjectStore_Upload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockObjectStore_Upload_Call) RunAndReturn(run func(ctx context.Context, request pkgrepo.UploadRequest) error) *MockObjectStore_Upload_Call {
	_c.Call.Return(run)
	return _c
}
